.eslintrc, .gitignore, index.html, package-lock.json, package.json, src/App.vue, src/index.ts, src/vite-env.d.ts, tsconfig.json, vite.config.ts
1. Added vite configuration
2. Added vue package
3. Added eslint
=> Added base project configuration

src/presentation/pages/Home.vue
=> fix: build docker image

src/presentation/styles/sizes.pcss
Add sizes for codex.web (border, spacing, layout, size-icon)
=> Styles: add sizes

src/infrastructure/transport/notes-api/index.ts
Fixed error while building docker image
=> Fixed building docker image

src/application/services/useNote.ts, src/domain/entities/Note.ts, src/presentation/pages/Note.vue
1. Added `Editor` to the note page
2. Changed content type of note to `OutputData`
3. Added `isLoading` to `useNote` hook
=> Added displaying note in Editor

src/presentation/layouts/Default.vue, src/vite-env.d.ts
Fix npm run build:
Add .env.types
Remove layout from default.vue
=> Fix build for layout

package-lock.json, package.json, src/App.vue, src/presentation/styles/colors.pcss
Duplicate https://github.com/codex-team/notes.web/pull/16/files
Because 16 pr has problem with git
=> Themes: add light | dark theme

src/application/services/useOAuth.ts, src/application/services/usePostMessage.ts, src/domain/auth.repository.interface.ts, src/domain/auth.service.ts, src/domain/event-bus/events/AuthCompleted.ts, src/domain/index.ts, src/infrastructure/auth.repository.ts, src/infrastructure/index.ts
Since Auth is a separate feature, I've separated it from user
=> chore: userService -> authService

src/application/services/useOAuth.ts, src/application/services/usePostMessage.ts, src/domain/auth.repository.interface.ts, src/domain/auth.service.ts, src/domain/index.ts, src/domain/note.repository.interface.ts, src/domain/user.repository.interface.ts, src/domain/user.service.ts, src/infrastructure/auth.repository.ts, src/infrastructure/index.ts, src/infrastructure/storage/note.ts, src/infrastructure/storage/user.ts, src/infrastructure/transport/authorizable.transport.ts, src/infrastructure/user.repository.ts
- Prepare UserService, Repo and Store
- Remove some debug logs
=> chore(user): user service created

.architecture.eslintrc, src/application/services/useAppState.ts, src/domain/auth.repository.interface.ts, src/domain/auth.service.ts, src/domain/entities/User.ts, src/domain/index.ts, src/domain/user.repository.interface.ts, src/domain/user.service.ts, src/infrastructure/auth.repository.ts, src/infrastructure/index.ts, src/infrastructure/repository.ts, src/infrastructure/storage/abstract/subscribable.ts, src/infrastructure/storage/base/subscribable.ts, src/infrastructure/storage/user.ts, src/infrastructure/transport/fetch.transport.ts, src/infrastructure/user.repository.ts, src/presentation/components/header/Header.vue, src/presentation/components/header/HeaderUser.vue, src/presentation/styles/sizes.pcss
- If we have stored refresh token, auth session will be refreshed
- If user is authenticated, show user picture in a header
- new concept "App State" — is a read-only combination of stores. It's created on Domain Level (since it creates Stores and knows about them). Application Services will have access to it. So they can react on store changes.
- SubscribableStore allows to watch data change. Any store could extend it.
- base class for Repository added
=> feat: app state, subscribable store, user panel, refresh session

src/application/services/useNote.ts, src/domain/note.repository.interface.ts, src/domain/note.service.ts, src/infrastructure/note.repository.ts
Saving changes in an already created Note.
Works on editor change. 
Sends PATCH /note request to the API. Related to https://github.com/codex-team/notes.api/pull/56
=> feat(note): update note logic implemented

package-lock.json, src/application/services/useLayout.ts, src/application/services/useNote.ts, src/application/services/useOAuth.ts, src/application/services/usePostMessage.ts, src/domain/auth.service.ts, src/domain/note.service.ts, src/infrastructure/note.repository.ts, src/infrastructure/transport/notes-api/index.ts, src/infrastructure/transport/notes-api/types/GetNoteResponsePayload.ts, src/vite-env.d.ts, yarn.lock
This PR fixes all ESLint errors
```bash
20:20  error  Unexpected any value in conditional. An explicit comparison or type cast is required  @typescript-eslint/strict-boolean-expressions
```
```bash
27:1  warning  Missing JSDoc @returns type  jsdoc/require-returns-type
```
```bash
37:1  warning  Missing JSDoc @returns type                                                           jsdoc/require-returns-type
80:9  error    Unexpected any value in conditional. An explicit comparison or type cast is required  @typescript-eslint/strict-boolean-expressions
114:9  error    Unexpected object value in conditional. The condition is always true                  @typescript-eslint/strict-boolean-expressions
```
```bash
24:1  warning  @param "endpoint" does not match an existing function parameter …
```
=> chore(build): eslint fix

src/application/services/useLayout.ts, src/application/services/useNoteSettings.ts, src/domain/index.ts
I'm not sure about useLayout. Because it's converted to string
=> Fix build: noteSettings

src/application/services/useNoteSettings.ts, src/presentation/pages/NoteSettings.vue
This PR fixes ESLint errors appeared after #52
=> fix(note-settings): eslint error fixed

src/domain/entities/NoteSettings.ts, src/infrastructure/noteSettings.repository.ts
set new url in request and added enabled to NoteSettings entity
=> fix: set new url in request and added enabled to NoteSettings entity

src/infrastructure/note.repository.ts
This PR fixes note editing. Working API introduced in https://github.com/codex-team/notes.api/pull/80
=> feat: edit note

src/application/services/useNoteSettings.ts, src/domain/noteSettings.repository.interface.ts, src/domain/noteSettings.service.ts, src/infrastructure/noteSettings.repository.ts, src/presentation/components/checkbox/Checkbox.vue, src/presentation/components/form/TextEdit.vue, src/presentation/pages/NoteSettings.vue
Added ability to change note settings
=> Feat: improved updating note settings

src/domain/entities/NoteSettings.ts, src/presentation/pages/NoteSettings.vue
renamed enabled field to isPublic
=> chore: renamed noteSettings.enabled to isPublic

.eslintrc, src/App.vue, src/application/i18n/messages/en.json, src/application/router/routes.ts, src/application/services/useLayout.ts, src/presentation/layouts/Fullpage.vue, src/presentation/pages/Error.vue
- Fixed "Layout" feature. Now it watches route change
- Added "Fullpage" layout. Use it for full width/height pages like landing, or error pages
- Added fallback route and Error Page
- Error Page could be used for any errors: 500, 404, etc
=> feat(router): 404 page

src/application/i18n/messages/en.json, src/application/services/useAppState.ts, src/application/services/useUserSettings.ts, src/domain/entities/EditorTool.ts, src/domain/user.repository.interface.ts, src/domain/user.service.ts, src/infrastructure/storage/user.ts, src/infrastructure/user.repository.ts, src/presentation/components/editor/Editor.vue, src/presentation/pages/Settings.vue
Show list of user editor tools. 
Default ones are included in user editor tools.
Allows to add tools to user by id in his settings.
=> feat: show editor tools in user settings

.github/workflows/eslint-check.yml, .github/workflows/send-test-results.yml
Make an api request to cancel workflow if all other flows were skipped/cancelled.
=> Change the way workflow stops

src/presentation/pages/Marketplace.vue, src/presentation/pages/Settings.vue
added `marketplace` button to user setting to redirect to `/marketplace`
=> feat: added marketplace button to user settings

codex-ui/src/styles/dimensions.pcss, codex-ui/src/styles/index.pcss, codex-ui/src/vue/button/Button.vue, codex-ui/src/vue/input/Input.vue
In the Design System we're organising all size-related tokens with variables. This PR adds those variables
=> feat(ui): dimensions tokens added

codex-ui/dev/Playground.vue, codex-ui/dev/TypeScale.vue, codex-ui/src/styles/dimensions.pcss, codex-ui/src/styles/typography.pcss, codex-ui/src/vue/button/Button.vue, codex-ui/src/vue/heading/Heading.vue, codex-ui/src/vue/input/Input.vue, codex-ui/vite.config.ts, src/presentation/pages/marketplace/AddTool.vue, src/presentation/styles/sizes.pcss
- Implement Button sizes: `small`, `medium`, `large`
- Fix letter-spacing in typography
- Setup CSS modules to disable hashing and use the `.cdx-` prefix (`_button_1yxsp_2 -> .cdx-button`)
=> feat(ui): button size

src/application/i18n/messages/en.json, src/application/services/useNoteSettings.ts, src/domain/noteSettings.repository.interface.ts, src/domain/noteSettings.service.ts, src/infrastructure/noteSettings.repository.ts, src/infrastructure/transport/fetch.transport.ts, src/presentation/pages/NoteSettings.vue
When the button is pressed, a new hash is generated
=> feature(noteSettings): revoke hash

src/application/i18n/messages/en.json, src/application/services/useNote.ts, src/domain/note.repository.interface.ts, src/domain/note.service.ts, src/infrastructure/note.repository.ts, src/infrastructure/transport/notes-api/types/GetNoteResponsePayload.ts, src/presentation/pages/Note.vue
What's done:
- now we can get parentNote form API
- button to unlink parent
- update button, that create child note
=> Feat: unlink parent

.github/workflows/send-test-results.yml
=> feat(CI): mention username and PR | branch on checks message to CodeX chat

codex-ui/dev/Playground.vue, codex-ui/dev/TypeScale.vue, codex-ui/src/styles/dimensions.pcss, codex-ui/src/styles/typography.pcss, codex-ui/src/vue/form/Field.vue, codex-ui/src/vue/index.ts, codex-ui/src/vue/row/Row.vue
=> Implement row component

.eslintrc, .gitignore, .vscode/settings.json, codex-ui/dev/Playground.vue, codex-ui/dev/TypeScale.vue, codex-ui/package.json, codex-ui/src/vue/button/Button.types.ts, codex-ui/src/vue/button/Button.vue, codex-ui/src/vue/button/index.ts, codex-ui/src/vue/form/Field.vue, codex-ui/src/vue/form/index.ts, codex-ui/src/vue/heading/index.ts, codex-ui/src/vue/input/Input.vue, codex-ui/src/vue/input/index.ts, codex-ui/src/vue/row/Row.vue, codex-ui/src/vue/row/index.ts, codex-ui/vite.config.ts, yarn.lock
Linting does not work out of the box in /codex-ui. 
Add `vscode/settings.json` with multiple eslint working directories
=> Fix lint in /codex-ui

codex-ui/src/vue/editor/Editor.vue, src/application/services/useAppState.ts, src/application/services/useMarketplace.ts, src/application/services/useUserTools.ts, src/presentation/pages/Note.vue
1) Wait for user tools to load before displaying editor
2) Add hardcoded header plugin styles
=> feat(note): add headers styles

codex-ui/src/vue/editor/Editor.vue
Hardcode styles for default blocks
=> feat(note): update note typography

src/application/i18n/messages/en.json, src/presentation/components/team/RoleSelect.vue, src/presentation/components/team/Team.vue
The list of collaborators has been modified using `FormSection` and `Row` components. Currently there is no custom selector and user avatar, only name.
=> feat(note-settings): note settings collaborators

src/application/i18n/messages/en.json, src/presentation/pages/NoteSettings.vue
Now we have new note settings availability, created by using `Section` and `Row` component
=> feat(note-settings): note settings availability

src/presentation/pages/NoteSettings.vue
Now we have switch component instead checkbox
=> feat(note-settings): Implement switch component to the note settings

src/application/services/useNote.ts
- Solved problem with Set(Array.prototype(object)), this set would not return array of unique objects, so we remove duplicates manually
=> chore[note]: improve note tools validation

src/application/i18n/messages/en.json, src/application/services/useNoteSettings.ts, src/domain/noteSettings.repository.interface.ts, src/domain/noteSettings.service.ts, src/infrastructure/noteSettings.repository.ts, src/presentation/pages/NoteSettings.vue
- now we can delete the note!
resolves #147
=> feat[note-settings]: added delete button

src/application/services/useLoadedTools.ts, src/application/services/useMergedTools.ts, src/application/services/useNote.ts, src/presentation/pages/Note.vue
=> fix: tools initialisation

codex-ui/dev/Playground.vue, codex-ui/src/vue/components/tabbar/Tab.types.ts, codex-ui/src/vue/components/tabbar/Tab.vue, codex-ui/src/vue/components/tabbar/Tabbar.vue, codex-ui/src/vue/components/tabbar/index.ts, src/presentation/components/header/Header.vue
emits in tabbar also tested with console.log()
=> feat(codex-ui): Tabbar component

codex-ui/src/vue/components/form/Field.vue, codex-ui/src/vue/components/input/Input.vue, src/application/i18n/messages/en.json, src/presentation/pages/Note.vue, src/presentation/pages/marketplace/AddTool.vue
=> feat: add simple add tool design

codex-ui/src/vue/components/tabbar/Tabbar.vue, src/presentation/components/header/Header.vue
=> using tabbar in header

codex-ui/dev/Playground.vue, codex-ui/dev/index.html, codex-ui/dev/pages/Index.vue, codex-ui/dev/pages/components/Button.vue, codex-ui/dev/pages/components/Input.vue, codex-ui/dev/pages/theming/BaseAndAccent.vue, codex-ui/dev/pages/theming/ColorScheme.vue, codex-ui/dev/routes.ts, codex-ui/package.json, codex-ui/src/vue/components/vertical-menu/VerticalMenu.types.ts, codex-ui/src/vue/components/vertical-menu/VerticalMenuItem.vue, yarn.lock
This is the second part of Playground update.
- Sidebar added using Vertical Menu
- VueRouter added 
- Component `VerticalMenu` now supports `onActivate` callback
In the next step I'll move all components from the Playground to separate pages
=> feat(playground): sidebar + router

src/presentation/components/header/Header.vue
Using tabbar for authorization in header
=> feat(header):using tabbar for authorization states in header

codex-ui/dev/pages/components/Card.vue, codex-ui/src/vue/components/card/Card.vue, codex-ui/src/vue/components/form/Fieldset.vue, src/application/i18n/messages/en.json, src/presentation/pages/Settings.vue
- Implemented user editor tools for user settings page
- Fixed card slot alignment
- Fixed fieldset gaps appearance
=> feat(settings): Implement editor tools for user settings page

codex-ui/dev/Playground.vue, codex-ui/dev/pages/components/Picture.vue, codex-ui/dev/pages/theming/ColorScheme.vue, codex-ui/dev/routes.ts, codex-ui/src/vue/components/picture/index.ts, codex-ui/src/vue/components/picture/picture.vue, codex-ui/src/vue/index.ts, src/presentation/pages/Settings.vue
- now we can use pictures from codex-ui by name
- also made minor fix for settings page
=> feat(codex-ui): set up picture component

codex-ui/dev/pages/theming/BaseAndAccent.vue, src/application/i18n/messages/en.json, src/presentation/pages/Settings.vue
This is 3-rd part of implementing user settings page 
Next i will do link to marketplace
- implemented theming in user settings page
- now using theme preview in codex-ui theming demo
=> feat(settings): implement appearance customization in user settings page

codex-ui/src/vue/components/row/Row.vue, src/application/i18n/messages/en.json, src/presentation/pages/Settings.vue
Now userSettings page has link to marketplace page
=> feat(settings): User settings link to marketplace

src/application/i18n/messages/en.json, src/application/services/useNoteSettings.ts, src/presentation/components/noteSettings/InviteLink.vue, src/presentation/pages/NoteSettings.vue
- Improve field, that shows join link
- Add copy button
- Add title to team section
=> feat(note-settings)/invite-collaborator-field

src/application/services/useNote.ts
1. Editor is not updated when moving from New Note page to another page
2. Page title is not updated after draft saving
1. There was a check for that case to prevent note "reload" if previous id is "null". It was not covered case when you simply goes from the draft to another note
2. `noteTitle()` computed getter depends on `lastUpdateContent` or `note`. They both was not updated in case of draft saving
1. Mark note saving process by `isNoteSaving()` flag. Thus we can explicitly distinguish two cases when draft is saved (don't reload note) and when draft is discarded (reload note)
2. update `lastUpdateContent()` on draft saving as well as regular saving
=> fix(note): refresh editor on draft discard, refresh page title on draft save

codex-ui/src/vue/components/editor/Editor.vue, src/infrastructure/utils/screenshot.ts, src/presentation/pages/Note.vue
Covers are not sent on note save
Code can't find editor element
I've exposed editor element from `ui/Editor.vue` and reference it.
=> fix(covers): cover sending fix

src/presentation/pages/NoteSettings.vue
=> chore(note-settings): note settings style fix

src/application/services/useAuthRequired.ts, src/infrastructure/auth.repository.ts, src/infrastructure/index.ts, src/infrastructure/storage/abstract/persistant.ts, src/infrastructure/storage/abstract/session.ts, src/infrastructure/storage/abstract/subscribable.ts, src/infrastructure/storage/auth.ts, src/infrastructure/storage/openedPage.ts, src/infrastructure/storage/user.ts
- implemented session store (it would be updated on page reload)
- implemented persistant store (it would not be updated on page reload), based on window.localStorage
- fixed login required logic (now when user is undefined, service will wait until user is null of actually user)
=> feat(store): session and persistant stores implemented

codex-ui/dev/pages/components/Card.vue, codex-ui/src/vue/components/card/CardSkeleton.vue, codex-ui/src/vue/components/card/index.ts, src/application/services/useNoteList.ts, src/presentation/components/note-list/NoteList.vue, src/presentation/pages/Home.vue
- Fix Home page reload after login/logout
- Add CardSkeleton component to the CodeX UI
- Display skeleton on loading of home page note list
=> fix(home): reloading after auth, skeleton

codex-ui/dev/pages/components/Checkbox.vue, codex-ui/src/vue/components/checkbox/Checkbox.vue, codex-ui/src/vue/components/checkbox/index.ts, codex-ui/src/vue/index.ts
Resolves #272
This PR implements the checkbox component for the Codex-UI as described in Issue #272.
- Created a new Checkbox component following the design provided in Figma.
- Added the component to `/codex-ui/src/vue/components`.
- Developed a demonstration page for the component in `/codex-ui/dev/pages`.
- Configured various states for the checkbox component (checked, unchecked, hover, disabled) according to the design specifications.
- Applied styles to match the Figma design.
This component includes multiple states, such as `hover`, `disabled`, `checked`, and `unchecked`, all controlled via props for maximum flexibility.
=> [Feature] Implement Checkbox Component for Codex-UI (#272)

codex-ui/src/vue/layout/navbar/Navbar.vue
fix-horisontal scroll
added overflow: hidden;
=> (fix) horisontal scroll appeared

src/application/services/useNavbar.ts, src/domain/workspace.repository.interface.ts, src/domain/workspace.service.ts, src/infrastructure/storage/openedPage.ts, src/infrastructure/workspace.repository.ts, src/presentation/pages/Settings.vue
fix: delete opened pages excluding home page on user logout
=> fix: clear local storage on logout

codex-ui/src/styles/z-axis.pcss, src/presentation/components/note-header/NoteHeader.vue
added position sticky to note header component
=> feat(ui): sticky note header

codex-ui/dev/pages/components/Editor.vue, codex-ui/src/vue/components/editor/Editor.vue, src/application/services/useNoteEditor.ts
* added inlineToolbar to Editor.js config
=> feat: inline-toolbar

src/presentation/components/team/Team.vue
- Add sortMembers function that sorts members in order Creator -> Writer -> Reader
- Change view to display team from sortedMember array
=> feat: Imp[NoteSettings] add func to sort team in correct order

package.json, yarn.lock
since `Hawk.javascript: 3.2.1` there added minified code filters to ignore source code with huge amount of symbols
resolves #310
=> deps(hawk-catcher): update package
