- package.json
- src/application/services/useLayout.ts
- src/application/services/useNote.ts
- src/domain/entities/Note.ts
- src/domain/note.repository.interface.ts
- src/domain/note.service.ts
- src/infrastructure/note.repository.ts
- src/infrastructure/storage/note.ts
- src/infrastructure/transport/notes-api/index.ts
- src/infrastructure/transport/notes-api/types/GetNoteResponsePayload.ts
- yarn.lock
1. Updated `eslint-config-codex` to the latest version
2. Errors fixed:
- If you import only type use `import type` instead of `import`
> chore(eslint): config updated, fixes

- src/domain/auth.service.ts
- src/infrastructure/auth.repository.ts
- src/infrastructure/storage/auth.ts
If the refresh token is expired, we get `Unhandled Promise Rejection` during  the `restoreSession()` call.
If we get the `Session is not valid` error during authorization, remove the invalid refresh token. Both form client store and API.
> chore(auth): when session is expired, removed it

- .eslintrc
- src/application/router/routes.ts
- src/application/services/useNote.ts
- src/domain/entities/Note.ts
- src/domain/note.repository.interface.ts
- src/domain/note.service.ts
- src/infrastructure/note.repository.ts
- src/infrastructure/storage/note.ts
- src/infrastructure/transport/notes-api/types/GetNoteResponsePayload.ts
- src/presentation/components/editor/Editor.vue
- src/presentation/components/header/Header.vue
- src/presentation/pages/Note.vue
1. When user presses "+", open `/new` route with an empty Editor filled with draft structure (empty title + paragraph).
2. When user types some chars, create a new Note by API and change path to the `/note/<id>`
3. When user presses "+" from the `/note/<id>` page, open `/new` with empty editor again.
For now, only note creation is implemented. Note updating will be implemented in the next PRs.
https://github.com/codex-team/notes.web/assets/3684889/09fd2f62-eafc-44bf-85a6-9be2a236bd92
> feat(note): create new note logic

- package.json
- src/application/services/useAppState.ts
- src/domain/index.ts
- src/infrastructure/repository.ts
This PR introduces two changes:
- setup TS type checking in dev mode which is [not included by default](https://vitejs.dev/guide/features.html#transpile-only)
- improve store-subscription method naming (`onStoreChange` -> `setStoreChangeCallback`)
- fix of the following error:
> fix(types): app state types improved

- src/domain/auth.service.ts
- src/domain/event-bus/events/AuthCompleted.ts
- src/domain/event-bus/index.ts
- src/infrastructure/index.ts
- src/presentation/components/editor/Editor.vue
- src/presentation/pages/Landing.vue
This PR fixes all remaining TS errors.
- Event Bus types improved. Previously, `addEventListener` did not support `CustomEvents`. Now we have an `Event Map` and augmentation of `addEventListener` to respect it.
- Errors `Could not find a declaration file for module '@editorjs/...'` suppressed and waiting till we rewrite Editor Tools to TypeScript
- "Landing" page (Note-by-hostname feature) temporarily commented. It should be reimplemented
> fix(ts): remaining ts errors fixed

- .github/workflows/build-check.yml
- .github/workflows/eslint-check.yml
Now workflows won't be triggered, when someone edit title or description.
> Deleted "edited" trigger

- src/application/services/useNote.ts
- src/domain/entities/NoteAccessRights.ts
- src/domain/note.repository.interface.ts
- src/domain/note.service.ts
- src/infrastructure/note.repository.ts
- src/infrastructure/transport/notes-api/types/GetNoteResponsePayload.ts
- src/presentation/components/editor/Editor.vue
- src/presentation/pages/Note.vue
This PR is related to pr122 in notes.api
Changes:
- added NoteAccessRights entity
- GetNoteResponsePayload now have { note: Note, accessRights: NoteAccessRights } structure
- NoteRepositoryInterface, NoteRepository, NoteService, UseNote updated to work with new note payload
- Removed cases when trying to get a note by its hostname could return null (because when the note is not found,   a    NotFoundError should be thrown)
> Added getting note access rights from note.api

- codex-ui/README.md
- codex-ui/dev/Playground.vue
- codex-ui/dev/index.html
- codex-ui/src/styles/fonts.pcss
- codex-ui/src/styles/index.pcss
- codex-ui/src/styles/themes/classic.pcss
- codex-ui/src/vue/button/Button.vue
- codex-ui/src/vue/heading/Heading.vue
- codex-ui/src/vue/input/Input.vue
- codex-ui/vite.config.ts
Now "codex-ui" package has a playground where we can implement and test components
- "yarn dev" now opens a playground
- Fonts setup added
- "Classic" theme colours updated
- "Button" and "Inputs" now uses colours from theme
- "Heading" component now supports 3 levels
> feat(ui): playground added

- src/App.vue
- src/application/services/useEditor.ts
- src/application/services/useNote.ts
- src/domain/note.repository.interface.ts
- src/domain/note.service.ts
- src/infrastructure/note.repository.ts
- src/presentation/components/editor/Editor.vue
- src/presentation/pages/Note.vue
- Update editor once page route changes to '/note/:noteId/new'
- Replace `alert` with `console.error` in global errors handler
- Move more logic to `useEditor`
> Fix create child note

- codex-ui/dev/Playground.vue
- codex-ui/src/styles/themes/classic.pcss
- codex-ui/src/styles/themes/crimson.pcss
- codex-ui/src/styles/themes/grass.pcss
- codex-ui/src/styles/themes/red.pcss
- codex-ui/src/styles/themes/violet.pcss
- codex-ui/src/vue/button/Button.vue
- Button can have one of 3 styles: `primary` (default), `secondary`, `destructive`
- Button can have one of 3 states: `default`, `hover`, `disabled`
- Color schemas now can be used not only for `body`, but for any element. `Red` scheme is used for `destructive` style
> feat(ui): button styles and states

- codex-ui/dev/Playground.vue
- codex-ui/src/vue/button/Button.vue
- codex-ui/src/vue/input/Input.vue
- Input sizes added: `small`, `medium`, `large`
- Input now can be disabled
- Button style now should be passed through the `style=secondary` instead of `secondary`. And other style as well. This change prevents possible style multiplication (`secondary destructive`)
> feat(ui): Input size

- codex-ui/dev/Playground.vue
- codex-ui/dev/index.html
- codex-ui/src/vue/form/Field.vue
- codex-ui/src/vue/form/Section.vue
- codex-ui/src/vue/index.ts
- codex-ui/src/vue/input/Input.vue
- FormField component added
- It support 3 sizes as well as Input and Button: `small`, `medium`, `large`
- Input component now has the `value` prop instead of `text`
- `v-model` added to the Input and Form Field components allowing to bind values
> feat(ui): form field

- src/application/i18n/messages/en.json
- src/application/services/useNoteSettings.ts
- src/domain/entities/Team.ts
- src/domain/noteSettings.repository.interface.ts
- src/domain/noteSettings.service.ts
- src/infrastructure/noteSettings.repository.ts
- src/presentation/components/team/Member.vue
- src/presentation/components/team/Team.vue
- src/presentation/pages/NoteSettings.vue
Now Note owner can change role of the team members (excluding his role) by using select component. It is not necessary to use the temporary `Save` button to save the data.
> feat(team): change team member role

- .github/workflows/eslint-check.yml
- codex-ui/package.json
- yarn.lock
Now Eslint checks codex-ui folder as well as the main app.
Resolves https://github.com/codex-team/notes.web/issues/157
> Add running eslint on CI in codex-ui

- src/application/services/useUserTools.ts
We had a problem that editor on new note page was initialising only after page reload because user tools were not updated. Fixed it
> Fix: fix editor not initialising after new note button press

- src/application/services/useNote.ts
- src/application/services/useTools.ts
- src/domain/entities/Note.ts
- src/domain/note.repository.interface.ts
- src/domain/note.service.ts
- src/infrastructure/note.repository.ts
- src/presentation/pages/Note.vue
- yarn.lock
```
noteTools: {
name: string,
id: string
}
```
now noteTools are not send to api on POST and PATCH /note, but they are required in body, that is why API returns 500
- added noteTools entity and noteTools formalizatoin for useNote service
- added noteTools, that are formed from content blocks ( via user tools )
- now on POST and PATCH /note `tools: noteTools` are included to body
> noteTools added for POST and PATCH /note

- src/application/i18n/messages/en.json
- src/presentation/pages/NoteSettings.vue
User can acidentally delete his note by pressing on delete button in note settings
Added confirmation window to make sure the user wants to delete the note
> chore[noteSettings]: added confirmation on note deleting

- .architecture.eslintrc
- eslint.config.mjs
- package.json
- src/application/services/useNoteSettings.ts
- src/domain/noteSettings.repository.interface.ts
- src/domain/noteSettings.service.ts
- src/infrastructure/noteSettings.repository.ts
- yarn.lock
Eslint-plugin-boudaries is not compatible with Eslint 9 (check this [issue](https://github.com/javierbrea/eslint-plugin-boundaries/issues/329) for actual information)
Since we migrate to eslint flatconfig format, `architecture.eslintrc` is not a case
also since `.eslintignore` is deprecated we need to specify ignore patterns for `architecture.eslint`
Added FlatCompat plugin to make `architecture.eslint` compatible with flatconfig format
Runned yarn lint:fix
> chore(eslint): compatibility with architecture.eslintrc

- src/application/services/useMergedTools.ts
> fix: return mergedTools as intended

- codex-ui/dev/Playground.vue
- codex-ui/src/vue/components/tabbar/Tab.types.ts
- codex-ui/src/vue/components/tabbar/Tab.vue
I'm gonna update CodeX UI Playground to make it more comfortable.
This is the first part of the update.
- Playground now has header
- Header has a logo and a Figma link
- Tab component now supports the `link` property to behave like a regular hyperlink.
> chore(playground): header added, tab component supports link

- src/infrastructure/utils/note.ts
Added checks for the .text property in the block
If block has no text, It should be Untitled
> fix: slice on undefined cause any

- codex-ui/dev/pages/components/Fieldset.vue
- codex-ui/src/vue/components/form/Fieldset.vue
- src/application/i18n/messages/en.json
- src/presentation/components/header/Header.vue
- src/presentation/pages/Settings.vue
this is the first part of implementation of the `User settings` page 
next time will do list of editor tools in user settings page
- user settings page first step of implementation
- style of the Fieldset component updated
- codestyle of the logo usage in header improved
> feat(settings): User settings page implementation

- src/application/i18n/messages/en.json
- src/application/services/useNote.ts
- src/application/services/useNoteSettings.ts
- src/presentation/pages/Note.vue
- src/presentation/pages/NoteSettings.vue
From now we can see parent note card in note settings page.
Also unlink button was removed from note page. Now you can unlink note from not settings page. 
ParentNote and setParent were moved to useNote
**With parent note**
**Without parent note**
> feat(note-settings)/parent-note-card

- codex-ui/dev/pages/components/ContextMenu.vue
- codex-ui/src/vue/components/context-menu/ContextMenu.types.ts
- codex-ui/src/vue/components/context-menu/ContextMenu.vue
- codex-ui/src/vue/components/context-menu/ContextMenuItem.vue
Now it is possible to search for an item among menu context items.
The items of show-case array has been modified to test the `context menu`.
Added a filtering feature that allows you to search among the `menu context` items. If the entered string is a substring of an item, it appears in the menu context. Separators remain between elements, but are removed from the beginning and end of the derived array.
If no item is found, the menu context displays the corresponding message.
> refactor(codex-ui):search in context menu

- codex-ui/dev/Playground.vue
- codex-ui/dev/pages/components/Popover.vue
- codex-ui/src/styles/index.pcss
- codex-ui/src/styles/z-axis.pcss
- codex-ui/src/vue/components/popover/Popover.types.ts
- codex-ui/src/vue/components/popover/Popover.vue
- codex-ui/src/vue/components/popover/index.ts
- codex-ui/src/vue/components/popover/usePopover.ts
- codex-ui/src/vue/index.ts
- src/App.vue
Popover component added.
1. Popover — the empty wrapper that can contain any component
2. It can be shown near a particular target element
3. Can be aligned vertically and horizontally 
4. Can be stretched to full width of a target element
5. Hides on clicks outside.
> feat(ui): popover

- codex-ui/package.json
- yarn.lock
When you open a page that you can't edit, you'll see an errors:
There were problems in Editor.js:
- it was calling `onChange()` on initialization in read-only mode
- it was calling `save()` internally on initialization in read-only mode
Problems was fixed on Editor.js side:
https://github.com/codex-team/editor.js/pull/2773
In this PR we just updating its version.
Also, Header tool updated as well with new placeholders
> fix(editor): errors on opening read-only pages

- codex-ui/dev/pages/Index.vue
- src/presentation/styles/reset.pcss
Placeholders in editor goes away in Safari
Our CSS `reset.pcss` sets input height to 100% 
I've removed input styles reset
> fix(editor): placeholders fixed

- codex-ui/src/vue/components/row/Row.vue
- src/presentation/pages/Settings.vue
Since row height is not fixed, it depends on content,
when we add icon `check` row's height becomes larger for some screens (`text-ui-base-medium` font-size set in rem, so for some screens font-size would be less or than 20px, so when icon added height of one certain row would be changed)
Now icon `check` is always displayed, but with opacity 0, for current theme with opacity 1
- with icon `check`
- without icon `check`
> chore(settings): fixed jumping theme changer

- src/application/i18n/messages/en.json
- src/application/router/routes.ts
- src/application/services/useNoteHistory.ts
- src/domain/entities/History.ts
- src/domain/index.ts
- src/domain/noteHistory.repository.interface.ts
- src/domain/noteHistory.service.ts
- src/infrastructure/index.ts
- src/infrastructure/noteHistory.repository.ts
- src/infrastructure/utils/date.ts
- src/infrastructure/utils/parseDate.ts
- src/presentation/components/note-list/NoteList.vue
- src/presentation/pages/History.vue
- src/presentation/pages/Note.vue
- src/presentation/pages/NoteSettings.vue
- added note history page
- added NoteHistory domain and application services
- added noteHistory repository
- added parseDate util
Will make note history button in note page and note history record clickable in next PR
> feat(note-history): added note-history page

- src/application/i18n/messages/en.json
- src/presentation/pages/NoteSettings.vue
For now Note settings title in tabbar duplicates note title
- Naming the tabbar `Note Settings` , and add watcher for noteTitle variable from UseNote() app service.
- Use patchOpenedPageByUrl() method from UseHeader() app service for patching title of note settings in tabbar.
> fix(tabbar): issue of tabbar duplicate of note setting fixed

- src/application/services/useNote.ts
- src/infrastructure/utils/note.ts
When the first input in the note contains spaces, the header of the note show `&nbsp;`. 
resolves #257 
The noteContent get stored as HTML entity. For this reason, the title shows the `&nbsp;`, whenever there is occurrence of space in the first block of the note.
- Target the return value of function in `useNote` service and replace all occurrences of `&nbsp;` with space.
- The change was made also on the `NoteList` where the bug occurs too.
> fix(&nbsp): a bug of header contains the &nbsp fixed

- codex-ui/dev/pages/components/Popover.vue
- codex-ui/src/vue/components/popover/Popover.vue
- codex-ui/src/vue/components/popover/usePopover.ts
Right now you can't call "hide" by click on the popover target element, because [onClickOutside](https://vueuse.org/core/onClickOutside/) will toggle isOpen back.
Now the target element will be ignored in onClickOutside
> fix(ui): popover toggle fix

- src/application/i18n/messages/en.json
- src/application/services/useNavbar.ts
- src/domain/workspace.repository.interface.ts
- src/infrastructure/storage/openedPage.ts
- src/infrastructure/workspace.repository.ts
- src/presentation/components/app-navbar/AppNavbar.vue
Home tab was integrated in tabbar for user to have ability to go to the home page (it is unclosable) when we did not have logo
Now we have logo to go to the home page, so home tab should not exist.
Solution:
As describe in issue https://github.com/codex-team/notes.web/issues/291, we will be removing home tab from the navbar and its special conditions.
Resolves https://github.com/codex-team/notes.web/issues/291
> Removed home page special permissions

- codex-ui/dev/pages/components/Select.vue
- codex-ui/src/vue/components/popover/Popover.vue
- codex-ui/src/vue/components/popover/usePopover.ts
- codex-ui/src/vue/components/select/Select.vue
- src/domain/entities/Note.ts
- src/presentation/components/team/RoleSelect.vue
- src/presentation/components/team/Team.vue
By this update Select Component was integrated into note's settings into Role Select component, which fixes #284. Due to this integration, some other little issues were fixed:
- added ability to get selected value outside the component via @value-update attribute
- changed Popover's reactive styling to avoid unapplying component's positioning
- Updated Select Component's page in Playground
> feat: select component integration

- @codexteam/ui/package.json
- @codexteam/ui/src/vue/layout/page-block/PageBlock.vue
On the NoteX Web if the right or left column is not rendered, the main layout shrinks unexpectedly.
Added a placeholder sidebar element with fixed width when the right or left column slot is empty. This ensures the layout remains consistent even if no content is provided for the right or left column.
> fix(marketplace): prevent layout shrink when right column is missing

- .github/workflows/npm-publish.yml
Description
Problem: CodeX UI lacks automated CI for publishing to npm
Changes: added CI workflow configuration for npm publish
> ci(codex-ui): add CI pipeline for npm publish

- src/application/services/useNote.ts
- src/domain/entities/NoteHierarchy.ts
- src/presentation/components/app-navbar/AppNavbar.vue
- src/presentation/pages/Note.vue
Note heirarchy changes for note title composer on backend
> chore(sidebar): use title from api instead of content-based
